spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:31672/postgres
        username: admin
        password: admin
custom:
    logging:
        enable: true
#    jpa:
#        properties:
#            hibernate:
#                format_sql: 'true'
#        show-sql: 'true'
